image: debian:buster

stages:
  - build

build:
  stage: build
  script:
    - apt-get update && apt-get install -qy apt-transport-https ca-certificates curl gnupg2 software-properties-common 
    - curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
    - apt-key fingerprint 0EBFCD88
    - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
    - apt-get update && apt-get install -qy docker-ce docker-ce-cli containerd.io
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - make all
