image: debian:buster

stages:
  - build

.build:
  stage: build
  script:
    - apt-get update && apt-get install -qy apt-transport-https ca-certificates curl gnupg2 software-properties-common sshpass
    - curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
    - apt-key fingerprint 0EBFCD88
    - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
    - apt-get update && apt-get install -qy docker-ce docker-ce-cli containerd.io
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - make build-version
    - if [ "${DOCKER_PUSH}" != "false" ]; then make push; fi
    - if [ "${CI_COMMIT_REF_NAME}" = "master" ]; then make version-tag; fi
    - if [ "${CI_COMMIT_REF_NAME}" = "master" ] && [ "${DOCKER_PUSH}" != "false" ]; then make push-latest; fi

include: nso-versions.yaml
