image: debian:buster

stages:
  - build
  - multiver-test
  - push

before_script:
  - if [ "$(which docker)" == "/usr/bin/docker" ]; then echo "Docker already installed"; else echo "Docker is not installed, installing..." && apt-get update && apt-get install -qy apt-transport-https ca-certificates curl gnupg2 software-properties-common sshpass && curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - && apt-key fingerprint 0EBFCD88 && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" && apt-get update && apt-get install -qy docker-ce docker-ce-cli containerd.io; fi

version-matrix:
  stage: build
  script:
    - apt-get update && apt-get install -qy git python3
    - cd version-includes
    - ./gen.py
    - git add -N .
    - git status
    - git diff
    - git diff --exit-code

.build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - make build-version
    - make test-version
    - if [ "${DOCKER_PUSH}" != "false" ]; then make push; fi

.multiver_test:
  stage: multiver-test
  script:
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - if [ "${DOCKER_PUSH}" != "false" ]; then make pull; fi
    - make test-version-multiver

.push:
  stage: push
  script:
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - if [ "${DOCKER_PUSH}" != "false" ]; then make pull; fi
    - if [ "${CI_COMMIT_REF_NAME}" = "master" ]; then make version-tag; fi
    - if [ "${CI_COMMIT_REF_NAME}" = "master" ] && [ "${DOCKER_PUSH}" != "false" ]; then make push-latest; fi

multiver-test_4.7.6_5.3:
  extends: .multiver_test
  variables:
    OLD_NSO_VERSION: "4.7.6"
    NSO_VERSION: "5.3"

multiver-test_5.2.1_5.3:
  extends: .multiver_test
  variables:
    OLD_NSO_VERSION: "5.2.1"
    NSO_VERSION: "5.3"

include:
  - 'version-includes/build-all.yaml'
  - 'version-includes/push-all.yaml'
